services:
  asynqmon:
    image: hibiken/asynqmon:latest
    platform: linux/amd64
    container_name: asynqmon
    restart: unless-stopped
    ports:
      - "${ASYNQMON_PORT}:8080"
    environment:
      - REDIS_ADDR=${REDIS_ADDR}
      - REDIS_DB=${REDIS_DB}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    # command: --redis-addr=host.docker.internal:6379/1
