services:
  tracing:
    image: jaegertracing/all-in-one:latest
    ports:
      # - "5775:5775/udp"   # Agent compact protocol
      # - 6831:6831/udp     # Agent UDP protocol
      # - 6832:6832/udp     # Agent binary thrift protocol
      # - 5778:5778         # Agent HTTP server
      - 16686:16686 # Jaeger UI
      - 4317:4317
      - 4318:4318
      # - 14250:14250       # Collector gRPC
      # - 14268:14268       # Collector HTTP
      # - 14269:14269
      - 9411:9411 # Zipkin compatibility

  # zookeeper:
  #   image: confluentinc/cp-zookeeper:latest
  #   container_name: zookeeper
  #   environment:
  #     ZOOKEEPER_CLIENT_PORT: 2181
  #     ZOOKEEPER_TICK_TIME: 2000
  #   ports:
  #     - "2181:2181"

  # kafka:
  #   image: confluentinc/cp-kafka:latest
  #   container_name: kafka
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   volumes:
  #     - ./kafka-data:/var/lib/kafka/data

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-ui
    ports:
      - "8080:8080"
    environment:
      - KAFKA_CLUSTERS_0_NAME=nedx-kafka-cluster
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_URL}
      - KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL=SASL_SSL
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM=PLAIN
      - KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG=org.apache.kafka.common.security.plain.PlainLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_LOCATION=/certs/ca-certificate.crt
      - KAFKA_CLUSTERS_0_PROPERTIES_SSL_TRUSTSTORE_TYPE=PEM
      # - KAFKA_CLUSTERS_0_PROPERTIES_CLIENT_ID=${KAFKA_CLIENT_ID}
      # - KAFKA_CLUSTERS_0_PROPERTIES_CONSUMER_GROUP_ID=${KAFKA_CONSUMER_GROUP_ID}
      # - KAFKA_CLUSTERS_0_TOPICS_0=${KAFKA_PREDICT_TOPIC}
      # - KAFKA_CLUSTERS_0_TOPICS_1=${KAFKA_PREDICT_ROUND_TOPIC}
    volumes:
      - ./certs:/certs:ro
    restart: always
