services:
  mongo-primary:
    image: mongo:8.0
    container_name: mongo-primary
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongo/certs/keyfile",
        "--tlsMode",
        "requireTLS",
        "--tlsCertificateKeyFile",
        "/etc/mongo/certs/mongodb.pem",
        "--tlsCAFile",
        "/etc/mongo/certs/ca.pem",
        "--tlsAllowInvalidHostnames",
        "--tlsAllowInvalidCertificates",
      ]
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 30s
      start_period: 0s
      start_interval: 1s
      retries: 30
    ports:
      - ${MONGO_PRIMARY_PORT}:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo-primary:/data/db
      - ./certs/keyfile:/etc/mongo/certs/keyfile:ro
      - ./certs/mongodb.pem:/etc/mongo/certs/mongodb.pem:ro
      - ./certs/ca.pem:/etc/mongo/certs/ca.pem:ro
    networks:
      - mongo-network

  mongo-secondary:
    image: mongo:8.0
    container_name: mongo-secondary
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongo/certs/keyfile",
        "--tlsMode",
        "requireTLS",
        "--tlsCertificateKeyFile",
        "/etc/mongo/certs/mongodb.pem",
        "--tlsCAFile",
        "/etc/mongo/certs/ca.pem",
        "--tlsAllowInvalidHostnames",
        "--tlsAllowInvalidCertificates",
      ]
    ports:
      - ${MONGO_SECONDARY_PORT}:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./data/mongo-secondary:/data/db
      - ./certs/keyfile:/etc/mongo/certs/keyfile:ro
      - ./certs/mongodb.pem:/etc/mongo/certs/mongodb.pem:ro
      - ./certs/ca.pem:/etc/mongo/certs/ca.pem:ro
    networks:
      - mongo-network

  mongo-arbiter:
    image: mongo:8.0
    container_name: mongo-arbiter
    command:
      [
        "mongod",
        "--replSet",
        "rs0",
        "--bind_ip_all",
        "--keyFile",
        "/etc/mongo/certs/keyfile",
        "--tlsMode",
        "requireTLS",
        "--tlsCertificateKeyFile",
        "/etc/mongo/certs/mongodb.pem",
        "--tlsCAFile",
        "/etc/mongo/certs/ca.pem",
        "--tlsAllowInvalidHostnames",
        "--tlsAllowInvalidCertificates",
      ]
    ports:
      - ${MONGO_ARBITER_PORT}:27017
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - ./certs/keyfile:/etc/mongo/certs/keyfile:ro
      - ./certs/mongodb.pem:/etc/mongo/certs/mongodb.pem:ro
      - ./certs/ca.pem:/etc/mongo/certs/ca.pem:ro
    networks:
      - mongo-network

  mongo-replica-init:
    image: mongo:8.0
    container_name: mongo-replica-init
    depends_on:
      - mongo-primary
      - mongo-secondary
      - mongo-arbiter
    volumes:
      - ./init/mongo-replica-init.sh:/docker-entrypoint-initdb.d/mongo-replica-init.sh:ro
      - ./certs/mongodb.pem:/etc/mongo/certs/mongodb.pem:ro
      - ./certs/ca.pem:/etc/mongo/certs/ca.pem:ro
    environment:
      - MONGO_PRIMARY_IP=${MONGO_PRIMARY_IP}
      - MONGO_PRIMARY_PORT=${MONGO_PRIMARY_PORT}
      - MONGO_SECONDARY_IP=${MONGO_SECONDARY_IP}
      - MONGO_SECONDARY_PORT=${MONGO_SECONDARY_PORT}
      - MONGO_ARBITER_IP=${MONGO_ARBITER_IP}
      - MONGO_ARBITER_PORT=${MONGO_ARBITER_PORT}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    entrypoint: ["/docker-entrypoint-initdb.d/mongo-replica-init.sh"]
    networks:
      - mongo-network

networks:
  mongo-network:
    driver: bridge
